FROM confluentinc/cp-schema-registry:8.1.0

USER root
RUN microdnf install -y jq && microdnf clean all

COPY schemas/ /opt/schemas/
COPY init-schemas.sh /opt/init-schemas.sh

COPY entrypoint.sh /opt/entrypoint.sh

RUN chmod +x /opt/init-schemas.sh /opt/entrypoint.sh

USER appuser

ENTRYPOINT ["/opt/entrypoint.sh"]
